from flask import Flask, jsonify, request
from flask_cors import CORS
from database import init_db, get_connection
import datetime

app = Flask(__name__, static_folder='static', static_url_path='')
CORS(app)

# Principal page
@app.route('/')
def index():
    return app.send_static_file('index.html')

# Status page
@app.route('/status')
def status():
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute('SELECT COUNT(*) as total FROM orders')
    result = cursor.fetchone()
    conn.close()
    return jsonify({
        "status": "online",
        "system": "Production Orders System",
        "version": "1.0.0",
        "total_orders": result["total"],
        "timestamp": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    })

# Orders page
@app.route('/orders', methods=['GET'])
def list_orders():
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute('SELECT * FROM orders ORDER BY id DESC')
    orders = cursor.fetchall()
    conn.close()
    return jsonify([dict(o) for o in orders])

# Factory page
@app.route('/factory/<WEG>')
def boas_vindas(WEG):
    return jsonify({
    "message": f"Welcome, {WEG}! OP System online."
    })

# GET - Search order by ID
@app.route('/orders/<int:order_id>', methods=['GET'])
def search_order(order_id): # order_id is int
    """
    Search a unique production order by the ID.
    
    URL parameters:
        order_id(int): order ID to be searched
        
    Return:
        200 + JSON of the order, if founded.
        404 + error message, if dont exist.
    """
    conn = get_connection()
    cursor = conn.cursor()
    
    # The '?' is replaced by the valeu of order_id in a secure way
    cursor.execute('SELECT * FROM orders WHERE id = ?', (order_id,))
    order = cursor.fetchone() # fetchone() return a unique register or None
    conn.close()
    
    if order is None:
        return jsonify({'error': f'Order {order_id} not found.'}), 404
    
    return jsonify(dict(order)), 200
    
# POST - Create new order production
@app.route('/orders', methods=['POST'])
def create_order():
    """
    Create a new order production by the JSON data sended.
    
    Waited Body(JSON):
        product(str): Product name. Required.
        quantity(int): Pieces quantity. Required, > 0.
        status(str): Optional. Pattern: 'Pendent'.
        
    Return:
        201 + JSON of the created order, in success case.
        400 + error message, if invalid data.
    """
    data = request.get_json()
    
    # Verify if body was sended and is a valid JSON
    if not data:
        return jsonify({'error': 'Ausent or invalid Body requisition.'}), 400
    
    # Verify required field 'product'
    product = data.get('product', '').strip()
    if not product:
        return jsonify({'error': 'Field "product" is required and cant be empty.'}) , 400

    # Verify required field 'quantity'
    quantity = data.get('quantity')
    if quantity is None:
        return jsonify({'error': 'Field "quantity" is required'}) , 400
    
    # Verify if quantity is a positive integer number
    try:
        quantity = int(quantity)
        if quantity <= 0:
            raise ValueError()
    except(ValueError, TypeError):
        return jsonify({'error': 'Field "quantity" is required to be a positive integer number.'}) , 400
    
    # Status is optional; use 'Pendent' if not informed
    valid_status = ['Pending', 'In Progress', 'Completed']
    status = data.get('status', 'Pending')
    if status not in valid_status:
        return jsonify({'error': f'Invalid status. Use:{valid_status}'}), 400
    
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(
        'INSERT INTO orders (product, quantity, status) VALUES (?, ?, ?)',
        (product, quantity, status)
    )
    conn.commit()
    
    # Recuperate the new ID automatically generated by the database
    new_id = cursor.lastrowid
    conn.close()
    
    # Searching the new register to complete return
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute('SELECT * FROM orders WHERE id = ?', (new_id,))
    new_order = cursor.fetchone()
    conn.close()
    
    # Return 201 Created with a complete register
    return jsonify(dict(new_order)), 201
    
# PUT - Update Order Status
@app.route('/orders/<int:order_id>', methods=['PUT'])
def order_update(order_id):
    """
    Update status of an existent order.
    URL parameter:
    order_id (int): ID of order to update.
    Body waited (JSON):
    status (str): New status. Values accepted:
    'Pending', 'In Progress', 'Completed'.
    Return:
    200 + JSON order updated.
    400 + error if invalid status.
    404 + error if order not found.
    """
    data = request.get_json()
    
    if not data:
        return jsonify({'error': 'Ausent or invalid Body requisition.'}), 400
    
    # Valid status field
    valid_status = ['Pending', 'In Progress', 'Completed']
    new_status = data.get('status', '').strip()
    
    if not new_status:
        return jsonify({'error': 'Field "status" is required.'}), 400
    
    if new_status not in valid_status:
        return jsonify({'error': f'Invalid status. Allowed values:{valid_status}'}), 400
    conn = get_connection()
    cursor = conn.cursor()
    
    # Verify if order exist before update
    cursor.execute('SELECT id FROM orders WHERE id = ?', (order_id,))
    if cursor.fetchone() is None:
        conn.close()
        return jsonify({'error': f'Order {order_id} not found.'}), 404
    
    # Execute update
    cursor.execute('UPDATE orders SET status = ? WHERE id = ?',(new_status, order_id))
    conn.commit()
    conn.close()
    
    # Return register updated
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute('SELECT * FROM orders WHERE id = ?', (order_id,))
    order_update = cursor.fetchone()
    conn.close()
    return jsonify(dict(order_update)), 200
    
# DELETE - Remove a order by ID
@app.route('/orders/<int:order_id>', methods=['DELETE'])
def order_remove(order_id):
    """
    Permanently remove a production order by ID.
    
    URL parameters:
        order_id(int): ID of order to be removed.
    
    Return:
        200 + confirmation message.
        404 + error if order not found.
    """
    conn = get_connection()
    cursor = conn.cursor()
    
    # Verify existence before delete
    cursor.execute('SELECT id, product FROM orders WHERE id = ?', (order_id,))
    order = cursor.fetchone()
    
    if order is None:
        conn.close()
        return jsonify({'error': f'Order {order_id} not found.'}), 404
    
    product_name = order['product']
    
    # Correct DELETE
    cursor.execute('DELETE FROM orders WHERE id = ?', (order_id,))
    
    conn.commit()
    conn.close()
    
    return jsonify({
        'message': f'Order {order_id} ({product_name}) removed successfully.',
        'removed_id': order_id
    }), 200
    
if __name__ == '__main__':
    init_db()
    app.run(debug=True, host='0.0.0.0', port=5000)